### ISSUE TITLE
Air Alarms dont trigger "Danger" or "Warning" states despite the sensors meeting the appropriate condition

### ISSUE THREAD

**Issue by ProphetCrow** [echo-station/echo-station#12]
We got bugged air alarms again, which breaks automated teg setups, and makes firelocks unreliable, as they'll only lock to extreme pressure on adjacent tiles. 

Allegedly there's an upstream fix for this and dV is waiting for the next merge to impliment

**Comment by redmushie** [comment]
I tried to find an upstream fix but couldn't really find it. Let me know if you happen to know which commit or if/when dV merged it so I can merge it.

**Comment by ProphetCrow** [comment]
this might be fixed but it feels unresponsive. will do further testing next playtest

**Comment by redmushie** [comment]
Yeah this one was fixed with last upstream merge, whoopsies
