### ISSUE TITLE
Door remotes are lacking extraordinary accesses

### ISSUE THREAD

**Issue by ProphetCrow** [echo-station/echo-station#19]
dV and wizden removed door remotes having extraordinary accesses, so instead of copying the head of "departments" access, its just departmental access

The consequences of this is that the command remote is now useless, as its the only one that can interact with command doors and thats *ALL* it interacts with. It also makes all door remotes unable to interact with maintenance access as a byproduct, so CE's and Atmos remotes are unable to secure maints doors. 

Its a nitpick and balance issue. I personally think the door remotes should match the access of the person who owns it (not holding it)

**Comment by redmushie** [comment]
These were the changes made upstream:
![image](https://github.com/user-attachments/assets/cef8d6d7-a062-4688-a71f-ca49439ba611)

So basically, we _had_ door remotes that work on your + the remote's access, to remotes that only work on their own access.

I do feel split between the original behavior making sense vs the new behavior making more sense. Note that this is **not** the captain door remote I'm talking about, that one had a separate change.
