### ISSUE TITLE
Recombine the EMAG

### ISSUE THREAD

**Issue by ProphetCrow** [echo-station/echo-station#44]
https://github.com/echo-station/echo-station/commit/4227c24454be11fab40f38ea3f2d5a264f1cb721

Cool concept on paper but it introduces potential balance problems and fucks with mapping. Separating the "break doors" and "break machine" function between two cards with 3 charges each indirectly buffs the emag and hurts map design.

With three charges dedicated to doors, you can almost thoughtlessly use the access override card and still have 3 spare "real" emag charges to use on whatever you wish.

Imagine these two scenarios. Captain's bedroom is behind two or three command doors. There is the energy pistol, spare ID, and captain's locker all within reach. With an access override card, you can b-line it straight to the captains room, and still have enough charges to unlock *ALL* lockers. 

Scenario two: Armory is behind at least three secure access doors. Nukies can buy both the emag and the access override card. They can emag straight into armory and emag 3 safes open within moments. 

https://discord.com/channels/1263024087647649853/1263031053627428885/1267665163226583172

**Comment by redmushie** [comment]
This post reads like it was written with one thought in mind. What alternatives have you considered? I see no mention of tweaking charges or cooldowns for example.

**Comment by ProphetCrow** [comment]
solved in https://github.com/echo-station/echo-station/pull/79
